### ISSUE TITLE
Where did the `dist` folder go?

### ISSUE THREAD

**Issue by GuillaumeFalourd** [tale/kubectl-action#10]
## Context

I updated the action from @v1 to @v1.3.0 and got the following error message:
```
Error: File not found: '/home/runner/_work/_actions/tale/kubectl-action/v1.3.0/dist/index.js'
```

I observed in the `main` branch that the `dist` folder isn't mapped anymore, but is referred in the `action.yaml` file (`dist/index.js`)

## How to reproduce the error

I was using the action like this and just updated it to use node 20 and remove Github Actions WARNING messages.

```
      - name: kubectl config
        uses: tale/kubectl-action@v1.3.0
        with:
          base64-kube-config: ${{ steps.kubeconfig.outputs.KUBE_CONFIG_CONTENT }}
          kubectl-version: v${{ inputs.kubernetes-cluster-version }}
```

Coming back to v1 resolved the issue, but `v1.3.0` tag and `main` branch should be updated.
