### ISSUE TITLE
Not using input.kubectl-version

### ISSUE THREAD

**Issue by hardillb** [tale/kubectl-action#2]
Trying to fix the kubectl version to 1.23.4 to workround https://github.com/aws/aws-cli/issues/6920

But getting the following error in the logs:

```
Run tale/kubectl-action@v1.0.2
  with:
    base64-kube-config: ***
    kubectl-version: v1.23.4
  env:
    AWS_DEFAULT_REGION: eu-west-1
    AWS_REGION: eu-west-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Run echo "/home/runner/work/_actions/tale/kubectl-action/v1.0.2" >> $GITHUB_PATH
  echo "/home/runner/work/_actions/tale/kubectl-action/v1.0.2" >> $GITHUB_PATH
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    AWS_DEFAULT_REGION: eu-west-1
    AWS_REGION: eu-west-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Run setup-kubectl.sh
  setup-kubectl.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    AWS_DEFAULT_REGION: eu-west-1
    AWS_REGION: eu-west-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
/home/runner/work/_actions/tale/kubectl-action/v1.0.2/setup-kubectl.sh: line 3: [https://dl.k8s.io/release/${{](https://dl.k8s.io/release/$%7B%7B) inputs.kubectl-version }}/bin/linux/amd64/kubectl: bad substitution
/home/runner/work/_actions/tale/kubectl-action/v1.0.2/setup-kubectl.sh: line 4: [https://dl.k8s.io/${{](https://dl.k8s.io/$%7B%7B) inputs.kubectl-version }}/bin/linux/amd64/kubectl.sha256: bad substitution
cat: kubectl.sha256: No such file or directory
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
mv: cannot stat 'kubectl': No such file or directory
Run login-kubectl.sh
  login-kubectl.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    AWS_DEFAULT_REGION: eu-west-1
    AWS_REGION: eu-west-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    BASE64_KUBE_CONFIG: ***
```
It's not downloading the version I'm asking for (and appears to be using the newer bundled version.
